export const fruits = [
    {
      id: 0,
      name: "naranja",
      type: "citricos",
      img: "./img/products/naranja.webp",
      price: "120",
    },
    {
      id: 1,
      name: "pomelo",
      type: "citricos",
      img: "./img/products/pomelo.webp",
      price: "140",
    },
    {
      id: 2,
      name: "mandarina",
      type: "citricos",
      img: "./img/products/mandarina.webp",
      price: "150",
    },
    {
      id: 3,
      name: "kiwi",
      type: "exoticas",
      img: "./img/products/kiwi.webp",
      price: "130",
    },
    {
      id: 4,
      name: "banana",
      type: "exoticas",
      img: "./img/products/banana.webp",
      price: "110",
    },
    {
      id: 5,
      name: "mango",
      type: "exoticas",
      img: "./img/products/mango.webp",
      price: "190",
    },
    {
      id: 6,
      name: "anana",
      type: "exoticas",
      img: "./img/products/anana.webp",
      price: "200",
    },
    {
      id: 7,
      name: "manzana",
      type: "dulces",
      img: "./img/products/manzana.webp",
      price: "210",
    },
    {
      id: 8,
      name: "pera",
      type: "dulces",
      img: "./img/products/pera.webp",
      price: "205",
    },
    {
      id: 9,
      name: "uva",
      type: "dulces",
      img: "./img/products/uva.webp",
      price: "160",
    },
    {
      id: 10,
      name: "almendra",
      type: "secos",
      img: "./img/products/almendra.webp",
      price: "150",
    },
    {
      id: 11,
      name: "nuez",
      type: "secos",
      img: "./img/products/nueces.webp",
      price: "130",
    },
    {
      id: 12,
      name: "avellana",
      type: "secos",
      img: "./img/products/avellanas.webp",
      price: "140",
    },
    {
      id: 13,
      name: "pistacho",
      type: "secos",
      img: "./img/products/pistacho.webp",
      price: "150",
    },
    {
      id: 14,
      name: "arandanos",
      type: "bayas",
      img: "./img/products/arandanos.webp",
      price: "160",
    },
    {
      id: 15,
      name: "fresa",
      type: "bayas",
      img: "./img/products/fresa.webp",
      price: "130",
    },
  ];